from ppo import arguments
from ppo.myPPOrun1 import run_ppo1
from ppo.myPPOrun2 import run_ppo
from ppo.myPPOrun4 import run_ppo4
from ppo.myPPOrun5 import run_ppo5
from ppo.mybodyPPOrun10 import run_mybodyppo10
from ppo.mybodyPPOrun11 import run_mybodyppo11
from ppo.metaPPOrun import run_metappo
from ppo.mygaPPOrun import run_gappo
from ppo.mygaPPOrun2 import run_gappo2
#from ppo.myPPOrun3 import run_ppo